import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Salmon Cookies</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Image
        src='/cookie-logo.png'
        width={300}
        height={300}
        alt='Salmon Cookies Logo'
      />
    </div>
  );
}
